#!/usr/bin/env python3

import colors as c

print(c.red + c.clear + '''who would cross the bridge of death 
must answer me these questions three 
'Ere the other side he see.''')

def prompt(question):
    print(question)
    answer = input('-->')
    return answer


name = prompt(c.blue + 'what is your name?')
quest = prompt('what is your quest?')
if name == 'ian':
    color = prompt(c.yellow + 'what is favorite color')

