#!/usr/bin/env python3
import colors as c


from utils import ask

print(c.clear + c.blue +"""welcome to madlibs.
enter your answers.
""")

text = '''
you will die in {female celebrity} hand's.the next she
will make out with you in a {vehicle}.next weak she finds 
another {boy} in his van.
'''

words = {
    "female celebrity" : None,
    "vehicle" : None,
    "boy" : None
}

for key in words:
    answer = ask("Enter " + key + ": ")
    words[key] = answer

print(text.format(**words))

