#!/usr/bin/env python3



import colors as c

print(c.red + c.clear + '''who would cross the bridge of death 
must answer me these questions three 
'Ere the other side he see.''')

def ask(question):
    print(question)
    answer = input('-->').lower().strip()
    return answer

def live():
    print('you live')

def die():
    print('have fun with the new game DIE')

name = ask(c.blue + 'what is your name?')
quest = ask('what is your quest?')
if name == 'ian' or name == 'drake':
    color = ask(c.yellow + 'what is favorite color')
    if color == 'blue':
        live()
    else:
        die()

elif name == 'robin':
    capitle == input('what is the capitle of cerie')

elif name == 'auther':
    answer = asask('what is the air speed vlocite of a swallow?')
    if answer == '24':
        live()
    elif swallow in ['what do you mean? an afican of urpon']:
        print('brige kepper die"s')
        live()
    else:
        die()

