#!/usr/bin/env python3

import colors as c
import fluffy as quiz
import random


print(c.clear)
print(quiz.intro)


while quiz.questions:
    question_functon = random.choice(quiz.questions)
    is_correct = question_functon()
    if is_correct:
        print("Right")
        quiz.questions.remove(question_functon)
    else:
        print("worng")
