#!/usr/bin/env python3
import colors as c
import time

hundredths = 1 

while True:
    print(c.clear)
    print(c.red + 'i love donuts' + c.reset)
    print(hundredths)
    hundredths += 1
    time.sleep(0.1)
